### ISSUE TITLE
Adding 1.78.0

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libboost-mpi-feedstock#6]
Recently we moved to Boost 1.78.0 globally in conda-forge ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3599 ). Would it be possible to add a `libboost-mpi` 1.78.0 as well?

**Comment by jakirkham** [comment]
Thoughts @conda-forge/libboost-mpi ? 🙂

**Comment by sdebionne** [comment]
Hi @jakirkham, this might sound silly, but I am not sure how to do that... I have already merged #5 but it sounds like it was not enough?

**Comment by jakirkham** [comment]
> this might sound silly, but I am not sure how to do that...

Normal way to handle this would be create a new branch (on `boost-cpp`, the branch name picked was [`v1.78.x`](https://github.com/conda-forge/boost-cpp-feedstock/tree/v1.78.x)) and then add a PR to change [the version packaged]( https://github.com/conda-forge/libboost-mpi-feedstock/blob/cb9daf1e093be922572d9efa15db9fcc6de90f7d/recipe/meta.yaml#L1 ) to be `1.78.0` (note: [the checksum]( https://github.com/conda-forge/libboost-mpi-feedstock/blob/cb9daf1e093be922572d9efa15db9fcc6de90f7d/recipe/meta.yaml#L10 ) may need to be updated as well). Then merge (assuming everything looks ok). Would also suggest enabling ABI migrations for that branch by [updating `conda-forge.yml` on `main`]( https://github.com/conda-forge/boost-cpp-feedstock/blob/54205be53367139c84b2b44ac4f0618a48506a12/conda-forge.yml#L1-L3 ). Here are [some more docs]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions ) (feel free to update anything that would improve clarity).

> I have already merged https://github.com/conda-forge/libboost-mpi-feedstock/pull/5 but it sounds like it was not enough?

That's odd actually as that bot PR doesn't really do anything as [the version is pinned]( https://github.com/conda-forge/libboost-mpi-feedstock/blob/cb9daf1e093be922572d9efa15db9fcc6de90f7d/recipe/meta.yaml#L26 ). Filed issue ( https://github.com/regro/cf-scripts/issues/1569 ) about this.

**Comment by jakirkham** [comment]
Linking this comment ( https://github.com/regro/cf-scripts/issues/1569#issuecomment-1315831473 ) from the No-op bot issue as it ties into ABI migrations and adding 1.78.0 (and future globally pinned versions)

**Comment by jakirkham** [comment]
Done by adding an `abi` branch for migrations with the changes in PR ( https://github.com/conda-forge/libboost-mpi-feedstock/pull/8 )
