### ISSUE TITLE
Headers don't appear to be included

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libboost-mpi-feedstock#9]
It appears only a dynamic library is in the package. The headers don't appear to be included.

Edit: This also depends on the resolution of upstream issue ( https://github.com/conda-forge/boost-cpp-feedstock/issues/131 ).

**Comment by sdebionne** [comment]
Yes, this is intended. This feedstock depends conda-forge/boost-cpp-feedstock that provides the headers.
